baseURL = "https://vayuuutn.com/"
languageCode = 'zh-cn'
title = '炸鱼薯条'
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
defaultTheme = "auto"
mainSections = ["posts"]

[params.homeInfoParams]
Title = ""
Content = """
1. 乐观的人永远前行
2. 我的努力会给她人和世界带来积极的影响
3. 我的过往不会成为我人生的判词
"""


[params.footer]
customText="@2025炸鱼薯条"

[params.assets]
customCSS = ["css/extra.css"]

[menu]

  [[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 2

  [[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 3

  [[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories"
  weight = 4

  [[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about"
  weight = 5
