baseURL = "https://vayuuutn.com/"
languageCode = 'en-us'
title = '炸鱼薯条'
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
defaultTheme = "auto"
mainSections = ["posts"]

[params.homeInfoParams]
Title = "欢迎来到炸鱼薯条的空间～"
Content = "这是用 Hugo + PaperMod 建立的个人网站。"


[params.footer]
customText="@2025炸鱼薯条"

[menu]

  [[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 2

  [[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 3

  [[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 4